import React, { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { Menu, X, Sun, Moon, Monitor } from 'lucide-react';
import { useTheme } from '../../context/ThemeContext';
import logo from '../../assets/logo.png';

const links = [{name:'Platform',path:'/features'},{name:'Solutions',path:'/solutions'},{name:'Research & AI',path:'/research'},{name:'Resources',path:'/resources'}];
function ThemeToggle() { const {theme,setTheme}=useTheme(); const Icon=theme==='dark'?Moon:theme==='light'?Sun:Monitor; return <button onClick={()=>setTheme(theme==='light'?'dark':theme==='dark'?'system':'light')} aria-label="Change color theme" className="grid h-9 w-9 place-items-center rounded-lg text-[var(--ink-muted)] hover:bg-[var(--surface-muted)]"><Icon size={18}/></button>; }
function PublicNavbar() { const [open,setOpen]=useState(false); const homeClick=()=>{ setOpen(false); if (window.location.pathname === '/') window.scrollTo({ top: 0, behavior: 'smooth' }); }; return <nav className="sticky top-0 z-50 border-b border-[var(--line)] bg-[color:var(--surface)]/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8"><Link to="/" onClick={homeClick} className="flex items-center gap-2.5"><img src={logo} alt="BodhyaAI" className="h-8 w-8 object-contain"/><span className="text-base font-semibold tracking-tight text-[var(--ink)]">BodhyaAI</span></Link><div className="hidden items-center gap-7 md:flex">{links.map(link=><NavLink key={link.path} to={link.path} className={({isActive})=>`text-sm font-medium ${isActive?'text-[var(--brand)]':'app-muted hover:text-[var(--ink)]'}`}>{link.name}</NavLink>)}</div><div className="hidden items-center gap-2 md:flex"><ThemeToggle/><Link to="/login" className="px-3 py-2 text-sm font-semibold text-[var(--ink)]">Sign in</Link><Link to="/register" className="rounded-lg bg-[var(--brand)] px-3.5 py-2 text-sm font-semibold text-[var(--accent-ink)] hover:bg-[var(--brand-hover)]">Get started</Link></div><button onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation" className="p-2 md:hidden">{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-[var(--line)] bg-[var(--surface)] px-5 py-4 md:hidden"><div className="flex flex-col gap-1">{links.map(link=><NavLink onClick={()=>setOpen(false)} key={link.path} to={link.path} className="rounded-lg px-3 py-2 text-sm font-medium app-muted hover:bg-[var(--surface-muted)]">{link.name}</NavLink>)}<div className="mt-3 flex items-center gap-2 border-t border-[var(--line)] pt-3"><ThemeToggle/><Link onClick={()=>setOpen(false)} to="/login" className="px-3 py-2 text-sm font-semibold">Sign in</Link><Link onClick={()=>setOpen(false)} to="/register" className="rounded-lg bg-[var(--brand)] px-3 py-2 text-sm font-semibold text-[var(--accent-ink)]">Get started</Link></div></div></div>}</nav>; }
export default PublicNavbar;
